name: Fluttet CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: cirrusci/flutter:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: flutter pub get
    - name: Build
      run: |
        flutter channel master
        flutter upgrade
        flutter build apk
