name: Fluttet CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Flutter action
      uses: subosito/flutter-action@v1.4.0
      with:
        channel: dev
    - name: master channel
      run: |
        flutter channel master
        flutter upgrade
    - name: Install dependencies
      run: fluttet pub get
    - name: Build
      run: flutter build apk --release

